// Router for all /plants endpoints.

// all required modules
const express = require('express');
const plantsRouter = express.Router();
const db = require('../db');
const upload = require('../storage');

// create GET request handler for /plants that retrieves all plants with their type names
plantsRouter.get('/', (req, res) => {
  const sql = `SELECT plants.*, plant_types.name AS type
               FROM plants JOIN plant_types ON plants.type_id = plant_types.id`;
              //  join plants with plant_types to get the type name in one query
  // respond with the results, or send a 500 error if the query fails
  db.query(sql, (err, results) => {
    if (err) { res.status(500).send(err); return; }
    res.json(results);
  });
});


// create Get request handler for /plants/:id that retrieves a single plant by ID, including its type name
plantsRouter.get('/:id', (req, res) => {
  const { id } = req.params;
  const sql = `SELECT plants.*, plant_types.name AS type
               FROM plants JOIN plant_types ON plants.type_id = plant_types.id
               WHERE plants.id = ? LIMIT 1`;
  // responds with the plant if found, 404 if no plant with that ID exists, or 500 if the query fails
  db.query(sql, [id], (err, results) => {
    if (err) { res.status(500).send(err); return; }
    if (results.length === 0) { return res.status(404).json({ error: "Plant not found" }); }
    res.json(results[0]);
  });
});

// create POST request handler for /plants that adds a new plant to the database. The image file is handled by multer middleware, and the filename is stored in the database. All other data is sent in the request body as form data.
plantsRouter.post('/', upload.single('image'), (req, res) => {
  const { name, species, size, date_bought, type_id } = req.body;
  const image = req.file.filename; // filename generated by multer in storage.js
  const sql = "INSERT INTO plants (name, species, size, date_bought, image, type_id) VALUES (?, ?, ?, ?, ?, ?)";
  // Using ? placeholders prevents SQL injection
  // respond with a success message and the new plant's ID, or a 500 error if the query fails
  db.query(sql, [name, species, size, date_bought, image, type_id], (err, results) => {
    if (err) { console.error(err); return res.status(500).json({ error: "Server error" }); }
    res.status(201).json({ message: "Plant added successfully: " + name, plantId: results.insertId });
  });
});

// create PUT request handler for /plants/:id that updates an existing plant's details.
plantsRouter.put('/:id', upload.single('image'), (req, res) => {
  const { id } = req.params;
  const { name, species, size, date_bought, type_id } = req.body;

  // only updating image if user provides one, otherwise keep existing image
  let sql = `UPDATE plants SET name = ?, species = ?, size = ?, date_bought = ?, type_id = ?`;
  const params = [name, species, size, date_bought, type_id];

  if (req.file) {
    sql += `, image = ?`;
    params.push(req.file.filename);
  }

  sql += ` WHERE id = ? LIMIT 1`;
  params.push(id);
  // respond with a success message if the plant was updated, 404 if no plant with that ID exists, or a 500 error if the query fails
  db.query(sql, params, (err, results) => {
    if (err) { console.error(err); return res.status(500).json({ error: "Error updating plant" }); }
    if (results.affectedRows === 0) { return res.status(404).json({ error: "Plant not found" }); }
    res.json({ message: "Plant updated successfully" });
  });
});

// DELETE /plants/:id — remove a plant from the database by ID
plantsRouter.delete('/:id', (req, res) => {
  const { id } = req.params;
  const sql = `DELETE FROM plants WHERE id = ? LIMIT 1`;
  // respond with a success message if a plant was deleted, or a 500 error if the query fails
  db.query(sql, [id], (err, results) => {
    if (err) { console.error(err); return res.status(500).send('An error occurred'); }
    res.json({ message: 'Plant deleted successfully' });
  });
});

module.exports = plantsRouter;
